### ISSUE TITLE
Historical Calibration of Jump-diffusion Models

### ISSUE THREAD

**Issue by waynelapierre** [rcalxrc08/FinancialCalibrator.jl#1]
I am looking for a package that could calibrate the parameters of jump-diffusion models, such as the Merton model and Kou model, based on asset returns. Will this package be a long-term project? I am very interested in it.

**Comment by rcalxrc08** [comment]
~~The functionality is already there.
The design is not amazing and the code is relying on some old interface of financialFFT library. I have no idea if this will be a long term project. I am more focusing on financialMontecarlo.jl so far.~~
If you notice this is not even a proper package although it contains most of the stuff that is needed for calibration.
If you want to contribute you are very welcome.

**Comment by rcalxrc08** [comment]
No actually I missed a piece. Calibration from asset returns is not yet implemented.
This library is more focused on "arbitrage free" pricing, where the calibration procedure involves the volatility surface but at a given time.

**Comment by waynelapierre** [comment]
If I need to calibrate the parameters of jump-diffusion models, such as the Merton model and Kou model, based on asset returns, is there a unified procedure for doing that, or there are different methods? Could you point me the right direction? I am lost about what to do.

**Comment by rcalxrc08** [comment]
I would suggest you to implement a max likelihood method based on the realisations of the returns.
You will need to estimate the probability distribution of you theoretical returns based on the parameters (initially guessed) of the distribution, and optimize the likelihood function wrt those parameters.
Tbh, very little of the functionality of this package would be useful.
